export type CuratedAlternative = {
  name: string;
  brand: string;
  url: string;
  priceEur: number | null;
  sustainabilityNote: string;
  co2SavingKg: number | null;
  euroSaving: number | null;
};

export type Product = {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  priceFrom: string;
  priceTo: string;
  warehouseName: string;
  warehouseCode: string;
  countryOfOrigin: string;
  packagingType: string;
  sameDay: boolean;
  nextDay: boolean;
  normalDelivery: boolean;
  co2Footprint: string;
  repairabilityScore: string;
  estimatedLifespanYears: string;
  materialRecyclablePct: string;
  ecoLabel: string;
  carbonNeutralCertified: string;
  packagingScore: string;
  materialTypeScore: string;
  warehouseInfraScore: string;
  subScore1: string;
  transportScore: string;
  logisticsPlausibilityScore: string;
  sellerHonestyScore: string;
  subScore2: string;
  finalSustainabilityScore: string;
  confidenceLevel: "High" | "Medium" | "Low" | "";
  missingDataGaps: string;
  claimRiskFlag: string;
  claimRiskReason: string;
  recommendedDeliveryDate: "Today" | "Next day" | "Standard" | "";
  deliveryImprovementPercent: string;
  greenerAlternativeProductId: string;
  bolCertified: boolean;
  ecoLabelScope: string;
  priceSustainabilityScore: string;
  alternativePriceDeltaEur: string;
  altPriceSavingEur: string;
  altCo2SavingKg: string;
  altGreenerPct: string;
  makeScore: string;
  lastScore: string;
  curatedAlternative?: CuratedAlternative;
};
